// This file is auto-generated by scripts/update-version.mjs
// Do not edit manually - changes will be overwritten at build time.
export const APP_VERSION = '0.28.0';
export const APP_BUILD_TIME = '2026-01-27T20:54:13.541Z';
export const APP_GIT_COMMIT = 'f761f1c';
